### ISSUE TITLE
Error to load

### ISSUE THREAD

**Issue by fredroo** [ebdrup/html2pdf.it#50]
Unable to load the address (null): https://www.multidocs.com.br/imprimir-boleto/?token=54f3c08378a8d0aab00dbf5c3516a69a9372a9fddb8261aad710aebaa487338e fail

**Comment by fredroo** [comment]
http://www.html2pdf.it/?url=https%3A%2F%2Fwww.multidocs.com.br%2Fimprimir-boleto%2F%3Ftoken%3D54f3c08378a8d0aab00dbf5c3516a69a9372a9fddb8261aad710aebaa487338e&download=false&format=A4&downloadToken=1470775322865&orientation=portrait&margin=1cm

**Comment by fredroo** [comment]
not work with ssl links

**Comment by edm00se** [comment]
False:
http://www.html2pdf.it/?url=https%3A%2F%2Fencrypted.google.com%2F&download=false&format=A4&downloadToken=1470944274933&orientation=portrait&margin=1cm

Looking more closely at things, the URL you are providing, actually performs a 301 redirect to the same URL as an `http://` address. Check your network inspector in DevTools and you can see the same.

For your case, since the origin is enforcing a non-https, I believe this to be the root cause.

Try again, this time with `http://...` and you can see it works.:
http://www.html2pdf.it/?url=http%3A%2F%2Fwww.multidocs.com.br%2Fimprimir-boleto%2F%3Ftoken%3D54f3c08378a8d0aab00dbf5c3516a69a9372a9fddb8261aad710aebaa487338e&download=false&format=A4&downloadToken=1470775322865&orientation=portrait&margin=1cm
